/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostRouteImport } from './routes/post'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MealIdRouteImport } from './routes/meal.$id'

const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealIdRoute = MealIdRouteImport.update({
  id: '/meal/$id',
  path: '/meal/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/splash': typeof SplashRoute
  '/meal/$id': typeof MealIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/splash': typeof SplashRoute
  '/meal/$id': typeof MealIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/splash': typeof SplashRoute
  '/meal/$id': typeof MealIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/login'
    | '/post'
    | '/profile'
    | '/splash'
    | '/meal/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/login'
    | '/post'
    | '/profile'
    | '/splash'
    | '/meal/$id'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/login'
    | '/post'
    | '/profile'
    | '/splash'
    | '/meal/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  PostRoute: typeof PostRoute
  ProfileRoute: typeof ProfileRoute
  SplashRoute: typeof SplashRoute
  MealIdRoute: typeof MealIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal/$id': {
      id: '/meal/$id'
      path: '/meal/$id'
      fullPath: '/meal/$id'
      preLoaderRoute: typeof MealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  PostRoute: PostRoute,
  ProfileRoute: ProfileRoute,
  SplashRoute: SplashRoute,
  MealIdRoute: MealIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
